# Generated by Django 4.1.2 on 2022-11-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydatabase',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
