# Generated by Django 4.1.2 on 2022-12-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mydatabase_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mydatabase',
            new_name='empdb',
        ),
        migrations.RenameField(
            model_name='empdb',
            old_name='course',
            new_name='designation',
        ),
    ]
